// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>SiLA.Provider</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace SiLA.Provider
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    /// <summary>
    /// Continuation task
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ContinuationTask
    {

        private string errorMessageField;

        private ContinuationTaskDefaultTask defaultTaskField;

        private List<ContinuationTaskTask> taskField;

        private ContinuationTaskSelectedTask selectedTaskField;

        private List<string> extensionField;

        /// <summary>
        /// Gets or sets the error message.
        /// </summary>
        /// <value>
        /// The error message.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }

        /// <summary>
        /// Gets or sets the default task.
        /// </summary>
        /// <value>
        /// The default task.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContinuationTaskDefaultTask DefaultTask
        {
            get
            {
                return this.defaultTaskField;
            }
            set
            {
                this.defaultTaskField = value;
            }
        }

        /// <summary>
        /// Gets or sets the task.
        /// </summary>
        /// <value>
        /// The task.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("Task", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<ContinuationTaskTask> Task
        {
            get
            {
                return this.taskField;
            }
            set
            {
                this.taskField = value;
            }
        }

        /// <summary>
        /// Gets or sets the selected task.
        /// </summary>
        /// <value>
        /// The selected task.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContinuationTaskSelectedTask SelectedTask
        {
            get
            {
                return this.selectedTaskField;
            }
            set
            {
                this.selectedTaskField = value;
            }
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("Extension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<string> Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }

    /// <summary>
    /// Continuation default task
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ContinuationTaskDefaultTask
    {

        private string taskTypeField;

        private string taskTextField;

        private string userInteractionTimeoutField;

        private List<string> extensionField;

        private bool automaticAfterTimeoutField;

        /// <summary>
        /// Gets or sets the type of the task.
        /// </summary>
        /// <value>
        /// The type of the task.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaskType
        {
            get
            {
                return this.taskTypeField;
            }
            set
            {
                this.taskTypeField = value;
            }
        }

        /// <summary>
        /// Gets or sets the task text.
        /// </summary>
        /// <value>
        /// The task text.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaskText
        {
            get
            {
                return this.taskTextField;
            }
            set
            {
                this.taskTextField = value;
            }
        }

        /// <summary>
        /// Gets or sets the user interaction timeout.
        /// </summary>
        /// <value>
        /// The user interaction timeout.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "duration")]
        public string UserInteractionTimeout
        {
            get
            {
                return this.userInteractionTimeoutField;
            }
            set
            {
                this.userInteractionTimeoutField = value;
            }
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("Extension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<string> Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether the task is automatic after timeout.
        /// </summary>
        /// <value>
        /// 	<c>true</c> if task is automatic after timeout; otherwise, <c>false</c>.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool AutomaticAfterTimeout
        {
            get
            {
                return this.automaticAfterTimeoutField;
            }
            set
            {
                this.automaticAfterTimeoutField = value;
            }
        }
    }

    /// <summary>
    /// Continuation task task
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ContinuationTaskTask
    {

        private string taskTypeField;

        private string taskTextField;

        private List<object> extensionField;

        /// <summary>
        /// Gets or sets the type of the task.
        /// </summary>
        /// <value>
        /// The type of the task.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaskType
        {
            get
            {
                return this.taskTypeField;
            }
            set
            {
                this.taskTypeField = value;
            }
        }

        /// <summary>
        /// Gets or sets the task text.
        /// </summary>
        /// <value>
        /// The task text.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaskText
        {
            get
            {
                return this.taskTextField;
            }
            set
            {
                this.taskTextField = value;
            }
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("Extension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<object> Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }

    /// <summary>
    /// The selected task of the continuation task
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ContinuationTaskSelectedTask
    {

        private string taskTypeField;

        private List<string> extensionField;

        /// <summary>
        /// Gets or sets the type of the task.
        /// </summary>
        /// <value>
        /// The type of the task.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaskType
        {
            get
            {
                return this.taskTypeField;
            }
            set
            {
                this.taskTypeField = value;
            }
        }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>
        /// The extension.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("Extension", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<string> Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
}
