// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>SiLA.Provider</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace SiLA.Provider
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    /// <summary>
    /// Parameter class
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Value", Namespace = "", IsNullable = true)]
    public partial class Parameter
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        private string nameField;

        private AllowedType parameterTypeField;

        private bool parameterTypeFieldSpecified;

        /// <summary>
        /// Gets or sets the item.
        /// </summary>
        /// <value>
        /// The item.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(bool), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Byte", typeof(sbyte), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(System.DateTime), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Duration", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "duration")]
        [System.Xml.Serialization.XmlElementAttribute("Float32", typeof(float), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Float64", typeof(double), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Int32", typeof(int), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Int64", typeof(long), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Short", typeof(short), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("String", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("unsignedByte", typeof(byte), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("unsignedInt", typeof(uint), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("unsignedLong", typeof(ulong), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("unsignedShort", typeof(ushort), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <summary>
        /// Gets or sets the name of the item element.
        /// </summary>
        /// <value>
        /// The name of the item element.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <summary>
        /// Gets or sets the type of the parameter.
        /// </summary>
        /// <value>
        /// The type of the parameter.
        /// </value>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AllowedType parameterType
        {
            get
            {
                return this.parameterTypeField;
            }
            set
            {
                this.parameterTypeField = value;
            }
        }

        /// <summary>
        /// Gets or sets a value indicating whether the parameter type is specified.
        /// </summary>
        /// <value>
        /// 	<c>true</c> if the parameter type is specified; otherwise, <c>false</c>.
        /// </value>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parameterTypeSpecified
        {
            get
            {
                return this.parameterTypeFieldSpecified;
            }
            set
            {
                this.parameterTypeFieldSpecified = value;
            }
        }
    }

    /// <summary>
    /// The type of the item choice
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemChoiceType
    {


        /// <summary>
        /// Boolean
        /// </summary>
        Boolean,

        /// <summary>
        /// Byte
        /// </summary>
        Byte,

        /// <summary>
        /// DateTime
        /// </summary>
        DateTime,

        /// <summary>
        /// Duration
        /// </summary>
        Duration,

        /// <summary>
        /// Float32
        /// </summary>
        Float32,

        /// <summary>
        /// Float64
        /// </summary>
        Float64,

        /// <summary>
        /// Int32
        /// </summary>
        Int32,

        /// <summary>
        /// Int64
        /// </summary>
        Int64,

        /// <summary>
        /// Short
        /// </summary>
        Short,

        /// <summary>
        /// String
        /// </summary>
        String,

        /// <summary>
        /// unsignedByte
        /// </summary>
        unsignedByte,

        /// <summary>
        /// unsignedInt
        /// </summary>
        unsignedInt,

        /// <summary>
        /// unsignedLong
        /// </summary>
        unsignedLong,

        /// <summary>
        /// unsignedShort
        /// </summary>
        unsignedShort,
    }

    /// <summary>
    /// The allowed types
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public enum AllowedType
    {

        /// <summary>
        /// Boolean
        /// </summary>
        Boolean,

        /// <summary>
        /// DateTime
        /// </summary>
        DateTime,

        /// <summary>
        /// Float32
        /// </summary>
        Float32,

        /// <summary>
        /// Float64
        /// </summary>
        Float64,

        /// <summary>
        /// Byte
        /// </summary>
        Byte,

        /// <summary>
        /// Short
        /// </summary>
        Short,

        /// <summary>
        /// Int32
        /// </summary>
        Int32,

        /// <summary>
        /// Int64
        /// </summary>
        Int64,

        /// <summary>
        /// unsignedByte
        /// </summary>
        unsignedByte,

        /// <summary>
        /// unsignedShort
        /// </summary>
        unsignedShort,

        /// <summary>
        /// unsignedInt
        /// </summary>
        unsignedInt,

        /// <summary>
        /// unsignedLong
        /// </summary>
        unsignedLong,

        /// <summary>
        /// String
        /// </summary>
        String,

        /// <summary>
        /// Duration
        /// </summary>
        Duration,
    }

    /// <summary>
    /// Parameter set
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class ParameterSet
    {

        private List<Parameter> parameterField;

        /// <summary>
        /// Gets or sets the parameter.
        /// </summary>
        /// <value>
        /// The parameter.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("Parameter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<Parameter> Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
    }

    /// <summary>
    /// Response data
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1026")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class ResponseData
    {

        private List<object> itemsField;

        /// <summary>
        /// Gets or sets the items.
        /// </summary>
        /// <value>
        /// The items.
        /// </value>
        [System.Xml.Serialization.XmlElementAttribute("AnyData", typeof(object), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("Parameter", typeof(Parameter), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("ParameterSet", typeof(ParameterSet), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
